table Products
	lineageTag: d088f83c-b855-4658-8e43-318f2297c28b

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 5f4d3690-ac0f-444e-a544-d27e87bc32c5
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: a03badc4-a701-4ec2-8a23-cd607840156f
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ProductCategoryID
		dataType: string
		lineageTag: a6fcb25c-45e7-495c-b883-2c89b2ab6491
		summarizeBy: none
		sourceColumn: ProductCategoryID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ProductGroupID
		dataType: string
		lineageTag: cac677e0-059f-474c-9e8d-baeed1d93e0f
		summarizeBy: none
		sourceColumn: ProductGroupID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Products-9388f36d-558c-4c5b-9e0b-6b2db7906933 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\OneDrive - kteam.ch\K TEAM\Kunden\Zebra BI\KB\Data sources\Sales_demo_DB.xlsx"), null, true),
				    Products_Table = Source{[Item="Products",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Products_Table,{{"ProductID", Int64.Type}, {"Product", type text}, {"ProductCategoryID", type text}, {"ProductGroupID", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

